#---------------
# edited by Anatolii Radchenko
#---------------
name: MyGithubActionsBasics
env:
  APPLICATION_NAME: "My_app"
  PACKAGE_NAME    : "app-deploy-ver-${{ github.sha }}"
  
#on: [push]
on:
  push:
    branches:
      - main

jobs:
  my-testing:
    runs-on: ubuntu-latest
    steps:
    - name: print hello message
      run: echo "hello world from test!"

    - name: exec vew commands
      run: |
        echo "hello msg:"
        echo "hello msg:"
        echo "app name: ${{ env.APPLICATION_NAME }}"
        echo "pkg name: ${{ env.PACKAGE_NAME }}"
    - name: exec vew commands
      run:  ls -la
        
      
  my-deploy:
    runs-on: ubuntu-latest
    needs: [my-testing]
    steps:
    - name: print hello message
      run: echo "hello world from deploy!"
    
